Update patch set 12
Patch Set 12:

> Patch Set 12:
> 
> > Patch Set 12:
> > 
> > > Patch Set 12:
> > > 
> > > Ah, TreeHugger catches one problem:
> > > 
> > > frameworks/base/services/core/java/com/android/server/net/watchlist/NetworkWatchlistService.java:142: error: <anonymous com.android.server.net.watchlist.NetworkWatchlistService$1> is not abstract and does not override abstract method onPrivateDnsValidationEvent(int,String,String,boolean) in INetdEventCallback
> > > private final INetdEventCallback mNetdEventCallback = new INetdEventCallback.Stub() {
> > > ^
> > > 1 error
> > 
> > Katharine noted this on March 1 above, "Presubmit shows successful builds for aosp-master but not for git_master. How should I resolve that?"
> > 
> > The code in question (NetworkWatchlistService) is not in aosp-master.  It's a one-line fix but it's a flag-day; we have to land in aosp-master and then combine the fix with a cherry-pick into git_master.  We don't know what the procedure is but we were hoping that you would know.
> 
> Ah, I missed that; my apologies.
> 
> In that case, the simplest approach is probably to proceed as follows:
> 
>     (a) merge an AOSP change that just adds BaseNetdEventCallback.java and associated refactoring (no dependency on netd changes)
> 
>     (b) after that flows through to master, I can send a change that fixes up this class in master/other branches
> 
> Then this change can just be the part that adds the new method to BaseNetdEventCallback. I think we should have achieved the right isolation by then.
> 
> Let me know which parts, if any, you'd like me to take care of.  I know these deck-chair-shuffling exercises are not fun.

I uploaded aosp/636999 which adds the BaseNetdEventCallback.java class for the existing INetdEventCallback methods. It would be helpful if you could take care of the change in NetworkWatchlistService once aosp/636999 gets to master. I haven't modified this cl at all since the split - I just plan to sync after aosp/636999 gets in.

Patch-set: 12
Reviewer: Gerrit User 1257168 <1257168@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0