Update patch set 1
Patch Set 1:

View.setFlags() had already checked that accessibility was enabled in
UI thread, but some other thread disabled accessibility that caused
system server crash.

----------

Root Cause Analysis: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.display

java.lang.IllegalStateException: Accessibility off. Did you forget to check that?

android.view.accessibility.AccessibilityManager.sendAccessibilityEvent(AccessibilityManager.java)

Call Stack: 
java.lang.IllegalStateException: Accessibility off. Did you forget to check that?
at android.view.accessibility.AccessibilityManager.sendAccessibilityEvent(AccessibilityManager.java:309)
at android.view.ViewRootImpl.requestSendAccessibilityEvent(ViewRootImpl.java:6595)
at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5861)
at android.view.View.sendAccessibilityEventUnchecked(View.java:5840)
at android.view.View$SendViewStateChangedAccessibilityEvent.run(View.java:22451)
at android.view.View$SendViewStateChangedAccessibilityEvent.runOrPost(View.java:22484)
at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:8812)
at android.view.View.setFlags(View.java:10772) // It had already checked accessibility is on.
at android.view.View.setVisibility(View.java:7453)
at com.android.internal.policy.PhoneWindow$DecorView.updateColorViewInt(PhoneWindow.java:3085)
at com.android.internal.policy.PhoneWindow$DecorView.updateColorViews(PhoneWindow.java:2948)
at com.android.internal.policy.PhoneWindow$DecorView.onApplyWindowInsets(PhoneWindow.java:2898)
at android.view.View.dispatchApplyWindowInsets(View.java:7278)
at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:6285)
at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:1334)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1424)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1162)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6229)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
at android.view.Choreographer.doCallbacks(Choreographer.java:676)
at android.view.Choreographer.doFrame(Choreographer.java:606)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:168)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.android.server.ServiceThread.run(ServiceThread.java:46)

Patch-set: 1
Reviewer: Gerrit User 1035211 <1035211@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0