Update patch set 2
Patch Set 2:

This broke builds starting from stage-aosp-master:

https://android-build.googleplex.com/builds/git_stage-aosp-master-linux-aosp_mips-eng/4153249/logs/build_error.log

with:

ERROR: /usr/local/google/buildbot/src/googleplex-android/stage-aosp-master/frameworks/base/tests/net/java/com/android/server/ConnectivityServiceTest.java:322.22: TRANSPORT_LOWPAN cannot be resolved to a variable

TRANSPORT_LOWPAN was introduced by https://android-review.googlesource.com/#/c/421003/ That change is correctly merged in AOSP. It has:

Merged-In: Ie4aa77496f8ff466fa1a5fbc556e9c029457a689

which might have caused the automerger to ignore it, but that's incorrect, since Ie4aa77496f8ff466fa1a5fbc556e9c029457a689 is only merged into master.

Patch-set: 2