An EOFException need to be throw when read at the end of a file.
Many MediaExtractor sniffers may read a heic file during scanFile,but after the first MediaExtractor sniffer read the heic file, the read position is already bigger than the marked value, so when the sencond sniffer try to read the heic file, InputStream have to reset, then 'Resetting to invalid mark' occurs.
So an EOFException need to be throw when read at the end of a file, to avoid the reset error.

CTS-on-GSI:
CtsMediaTestCases--android.media.cts.MediaScannerTest#testEncodingDetection fail
CtsMediaTestCases--android.media.cts.MediaScannerTest#testMediaScanner fail

[Android Version]:
VTS Version 9.0_r7

[CTS pachage version]
Suite / PlanVTS / cts-on-gsi
Suite / Build9.0_R7

[device](Any device config may relate this failure)
unisoc's device
size:1080*1920

[bugzilla bugid] 129834453

[CTS Test Pre?Condition]
1.Language set to EN;
2.Keyguard set to none;
3.Enable GPS, Wifi network, USB debugging, Stay awake, Allow mock locations.
4.CTS version is VTS / cts-on-gsi 9.0_r7

[CTS Test Step]:
1 ./vts-tradefed
2 run cts-on-gsi

[Expected Result  ]:
This case will pass.

[Testing Result]:
case failed:
CtsMediaTestCases--android.media.cts.MediaScannerTest#testEncodingDetection fail
CtsMediaTestCases--android.media.cts.MediaScannerTest#testMediaScanner fail

[Analysize]:
log:
07-30 12:21:07.795   364   489 E FrameDecoder: Unable to convert from format 0x00000015 to 0x7f00a000
07-30 12:21:07.795   364   489 E FrameDecoder: failed to get video frame (err -1010)
From the log, we find the testcase is related with colorformat.

Bug #117044023

[root cause]:
1. During CtsMediaTestCases--android.media.cts.HeifWriterTest, a file named output.heic is generated under directory '/storage/emulated/0'.
2. During CtsMediaTestCases--android.media.cts.MediaScannerTest#testMediaScanner, MediaScanner begin to scan directory '/storage/emulated/0', when scanning output.heic, an error occurs, which caused the testMediaScanner to fail:
01-01 02:11:51.710   430   479 E StagefrightMetadataRetriever: Failed to instantiate a MediaExtractor.
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: An exception was thrown by callback 'scanFile'.
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: java.lang.RuntimeException: setDataSourceCallback failed: status = 0x80000000
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at android.media.MediaMetadataRetriever._setDataSource(Native Method)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:209)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at android.media.ExifInterface.getHeifAttributes(ExifInterface.java:2528)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at android.media.ExifInterface.loadAttributes(ExifInterface.java:1701)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at android.media.ExifInterface.<init>(ExifInterface.java:1341)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at android.media.MediaScanner.endFile(MediaScanner.java:962)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at android.media.MediaScanner.doScanFile(MediaScanner.java:655)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at android.media.MediaScanner.scanFile(MediaScanner.java:581)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at android.media.MediaScanner.processDirectory(Native Method)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at android.media.MediaScanner.scanDirectories(MediaScanner.java:1365)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at com.android.providers.media.MediaScannerService.scan(MediaScannerService.java:83)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at com.android.providers.media.MediaScannerService.access00(MediaScannerService.java:47)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at com.android.providers.media.MediaScannerService.handleMessage(MediaScannerService.java:258)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at android.os.Handler.dispatchMessage(Handler.java:106)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at android.os.Looper.loop(Looper.java:193)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at com.android.providers.media.MediaScannerService.run(MediaScannerService.java:162)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: at java.lang.Thread.run(Thread.java:764)
01-01 02:11:51.713  1330  8181 E MediaScannerJNI: An error occurred while scanning directory '/storage/emulated/0'.

01-01 02:11:51.758  8149  8180 I TestRunner: failed: testMediaScanner(android.media.cts.MediaScannerTest)
01-01 02:11:51.759  8149  8180 I TestRunner: ----- begin exception -----
01-01 02:11:51.759  8149  8180 I TestRunner: junit.framework.AssertionFailedError: expected:<1> but was:<0>
01-01 02:11:51.759  8149  8180 I TestRunner: at junit.framework.Assert.fail(Assert.java:50)
01-01 02:11:51.759  8149  8180 I TestRunner: at junit.framework.Assert.failNotEquals(Assert.java:287)
01-01 02:11:51.759  8149  8180 I TestRunner: at junit.framework.Assert.assertEquals(Assert.java:67)
01-01 02:11:51.759  8149  8180 I TestRunner: at junit.framework.Assert.assertEquals(Assert.java:199)
01-01 02:11:51.759  8149  8180 I TestRunner: at junit.framework.Assert.assertEquals(Assert.java:205)
01-01 02:11:51.759  8149  8180 I TestRunner: at android.media.cts.MediaScannerTest.testMediaScanner(MediaScannerTest.java:263)

3. We know that many MediaExtractor sniffers may read a heic file during scanFile. We find that these two cts cases will pass if Mpeg4Extractor sniffer is the first one to read output.heic, but if the other sniffers already read output.heic before Mpeg4Extractor sniffer, these two cts cases will always fail.
We add some logs in ExifInterface.java(in attachment), and find that the issue is 'Resetting to invalid mark' when doing mDataInputStream.reset().

From ExifInterface.java we can see that the readlimit of mark function is setted as mLength:
mDataInputStream.mark(mLength);
but after the first MediaExtractor sniffer readAt output.heic, the read position is already bigger than the marked value(mLength), so when the sencond sniffer try to readAt output.heic, mDataInputStream have to reset, then 'Resetting to invalid mark' occurs:
if (mPosition > byteCount) {
mPosition = 0;
mDataInputStream.reset();
mDataInputStream.mark(mLength);
}

Here is the error log we get, the size of output.heic is 23881 bytes:
//Some other sniffer readAt output.heic:
04-01 10:39:52.962  1267  1373 E ExifInterface: position = 0; offset = 0; size = 2048; mPosition = 0
04-01 10:39:53.053  1267  1373 E ExifInterface: position = 19402; offset = 0; size = 2048; mPosition = 21721
//mPosition > byteCount, then do mDataInputStream.mark(mLength), mLength is 23881:
04-01 10:39:53.054  1267  1373 D ExifInterface: seek, after mark, mLength = 23881
04-01 10:39:53.056  1267  1373 E ExifInterface: position = 22270; offset = 0; size = 2048; mPosition = 21450
04-01 10:39:53.058  1267  1373 E ExifInterface: position = 23881; offset = 0; size = 437; mPosition = 23881
//the read position now is 23883, which is bigger than the marked value(23881), then have to reset, but 'Resetting to invalid mark' error occurs:
04-01 10:39:53.060  1267  1373 E ExifInterface: position = 21453; offset = 0; size = 2048; mPosition = -1
04-01 10:39:53.060  1267  1373 E ExifInterface: before seek
04-01 10:39:53.060  1267  1373 D ExifInterface: seek, mPosition = 23883
04-01 10:39:53.060  1267  1373 D ExifInterface: seek, byteCount = 21453
04-01 10:39:53.060  1267  1373 D ExifInterface: seek, before reset
04-01 10:39:53.061  1267  1373 E ExifInterface: e = java.io.IOException: Resetting to invalid mark
//MPEG4Extractor sniffer begin to readAt output.heic, also get a 'Resetting to invalid mark' error:
04-01 10:39:53.064   428  1136 V MPEG4Extractor: MPEG4, Sniff size -1
04-01 10:39:53.064   428  1136 E MPEG4Extractor: BetterSniffMPEG4, offset = 0
04-01 10:39:53.065  1267  1373 E ExifInterface: position = 0; offset = 0; size = 2048; mPosition = -1
04-01 10:39:53.065  1267  1373 E ExifInterface: before seek
04-01 10:39:53.065  1267  1373 D ExifInterface: seek, mPosition = 21445
04-01 10:39:53.065  1267  1373 D ExifInterface: seek, byteCount = 0
04-01 10:39:53.065  1267  1373 D ExifInterface: seek, before reset
04-01 10:39:53.066  1267  1373 E ExifInterface: e = java.io.IOException: Resetting to invalid mark

[changes]:
We think the root cause of the cts fails is read position is already bigger than marked position when doing reset, so the read function don't have to do mDataInputStream.read() when read at the end of a file, so our solution is:

Change-Id: I5bd7c01c6a085d164de0e761e016b9d0167ac32d