Fix HSUM race condition: Defer user switch until User 0 unlocked
In Headless System User Mode (HSUM), CarMediaService crashes during boot with the error:
IllegalStateException: User 10 must be unlocked before calling this method.
This occurs when User 10 (foreground user) is unlocked before system user unlock.
To resolve this issue, add a deferral check in ActivityTaskSupervisor.activityIdleInternal() so that the system user (User 0) is fully unlocked before allowing non-system users to be unlocked during boot.

Bug: 517986252
Test: manual testing

Change-Id: I08a84a7c0e3913597eeaf654a0f29ded759cd24b
Signed-off-by: Jingtao Liu <JLIU298@ford.com>