Disable sandboxing on framework-doc-stubs and framework-doc-system-stubs
These fail with missing class errors when sandboxed:
frameworks/base/core/java/android/ddm/DdmHandleAppName.java:94: error: Class android.ddm.DdmHandleAppName.Names is not public but was referenced (as return type) from public method android.ddm.DdmHandleAppName.getNames() [ReferencesHidden]
frameworks/base/core/java/android/hardware/camera2/impl/CameraDeviceImpl.java:1778: error: Class android.hardware.camera2.impl.CaptureResultExtras is hidden but was referenced (as parameter type) from public parameter resultExtras in android.hardware.camera2.impl.CameraDeviceImpl.CameraDeviceCallbacks.onDeviceError(int errorCode, android.hardware.camera2.impl.CaptureResultExtras resultExtras) [ReferencesHidden]

Bug: 153703940
Test: m framework-doc-stubs framework-doc-system-stubs
Change-Id: Ib4f4e5b15bed35ae0b1a6b8854bf02723e03f53b