Update patch set 3
Patch Set 3: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in AOSP.
  The following snippet of `git apply` output may point you in the right direction:
error: patch failed: core/res/res/values/strings.xml:97
error: core/res/res/values/strings.xml: patch does not apply
error: patch failed: telephony/java/com/android/internal/telephony/ITelephony.aidl:278
error: telephony/java/com/android/internal/telephony/ITelephony.aidl: patch does not apply
error: telephony/java/com/android/internal/telephony/IccCard.java: No such file or directory
error: telephony/java/com/android/internal/telephony/gsm/GsmMmiCode.java: No such file or directory


Patchset creates merge conflict in Google's internal tree.

If you wish to pursue this change, please rebase and upload a new patchset.

Patch-set: 3
Reviewer: Gerrit User 1006433 <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=0
Label: Verified=-1