Update patch set 13
Patch Set 13: Presubmit-Verified-1

=== Finished presubmit run: L70700000093260115 ===

Status: https://android-build.googleplex.com/builds/where-is-my-cl/android-review/370652?revision=13




FAIL: Some checks failed. See below.


=== aosp-master/aosp_arm64-eng ===

PASS: Built aosp-master/aosp_arm64-eng/4275263 (ToT). See https://android-build.googleplex.com/builds/pending/P4675035/aosp_arm64-eng/latest


=== aosp-master/aosp_x86-eng ===

PASS: Built aosp-master/aosp_x86-eng/4275263 (ToT). See https://android-build.googleplex.com/builds/pending/P4675023/aosp_x86-eng/latest


=== git_master/bullhead-userdebug_fastbuild3a_linux ===

SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4274845 (LKGB). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux
SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4274845 (LKGB). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux
SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4274845 (LKGB). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux
SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4274845 (LKGB). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux
SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4275271 (ToT). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when bullhead-userdebug_fastbuild3a_linux is green.
SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4275271 (ToT). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when bullhead-userdebug_fastbuild3a_linux is green.
SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4275271 (ToT). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when bullhead-userdebug_fastbuild3a_linux is green.
SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4275271 (ToT). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when bullhead-userdebug_fastbuild3a_linux is green.
CONFLICT: Your changes failed to cherry-pick against build 4274845 (could not apply 3558538... Add ConnectivityManagerTest for Network.openConnection()). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4675034/bullhead-userdebug_fastbuild3a_linux/latest and search for "could not apply". NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq
CONFLICT: Your changes failed to cherry-pick against build 4275271 (could not apply 3558538... Add ConnectivityManagerTest for Network.openConnection()). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4675036/bullhead-userdebug_fastbuild3a_linux/latest and search for "could not apply". NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when bullhead-userdebug_fastbuild3a_linux is green.
WARNING: The tip-of-tree(4275271) for git_master/bullhead-userdebug_fastbuild3a_linux may be broken.
Presubmit builds based on the tip-of-tree (4275271) and the
last-known-good-build(4274845) also fail. This could be due to the
pre-existing error, a new error in this change, or both.



=== git_master/errorprone_fastbuild3e_linux ===

CONFLICT: Your changes failed to cherry-pick against build 4274798 (\'ETIMEDOUT\' was not declared in this scope".). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4675022/errorprone_fastbuild3e_linux/latest and search for "could not apply". NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq
CONFLICT: Your changes failed to cherry-pick against build 4275271 (could not apply 3558538... Add ConnectivityManagerTest for Network.openConnection()). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4675028/errorprone_fastbuild3e_linux/latest and search for "could not apply". NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when errorprone_fastbuild3e_linux is green.
WARNING: The tip-of-tree(4275271) for git_master/errorprone_fastbuild3e_linux may be broken.
Presubmit builds based on the tip-of-tree (4275271) and the
last-known-good-build(4274798) also fail. This could be due to the
pre-existing error, a new error in this change, or both.



=== git_master/gce_x86_phone-userdebug_fastbuild3c_linux ===

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4274798 (LKGB). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4274798 (LKGB). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4274798 (LKGB). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4274798 (LKGB). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4274798 (LKGB). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4274798 (LKGB). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4274798 (LKGB). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4274798 (LKGB). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4274798 (LKGB). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4274798 (LKGB). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4275271 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when gce_x86_phone-userdebug_fastbuild3c_linux is green.
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4275271 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when gce_x86_phone-userdebug_fastbuild3c_linux is green.
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4275271 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when gce_x86_phone-userdebug_fastbuild3c_linux is green.
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4275271 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when gce_x86_phone-userdebug_fastbuild3c_linux is green.
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4275271 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when gce_x86_phone-userdebug_fastbuild3c_linux is green.
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4275271 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when gce_x86_phone-userdebug_fastbuild3c_linux is green.
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4275271 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when gce_x86_phone-userdebug_fastbuild3c_linux is green.
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4275271 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when gce_x86_phone-userdebug_fastbuild3c_linux is green.
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4275271 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when gce_x86_phone-userdebug_fastbuild3c_linux is green.
SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4275271 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when gce_x86_phone-userdebug_fastbuild3c_linux is green.
CONFLICT: Your changes failed to cherry-pick against build 4274798 (could not apply 3558538... Add ConnectivityManagerTest for Network.openConnection()). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4675029/gce_x86_phone-userdebug_fastbuild3c_linux/latest and search for "could not apply". NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq
CONFLICT: Your changes failed to cherry-pick against build 4274798 (could not apply 3558538... Add ConnectivityManagerTest for Network.openConnection()). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4675030/test_suites_x86_64_fastbuild3d_linux/latest and search for "could not apply"
CONFLICT: Your changes failed to cherry-pick against build 4275271 (could not apply 3558538... Add ConnectivityManagerTest for Network.openConnection()). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4675024/gce_x86_phone-userdebug_fastbuild3c_linux/latest and search for "could not apply". NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq. WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when gce_x86_phone-userdebug_fastbuild3c_linux is green.
CONFLICT: Your changes failed to cherry-pick against build 4275271 (could not apply 3558538... Add ConnectivityManagerTest for Network.openConnection()). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4675027/test_suites_x86_64_fastbuild3d_linux/latest and search for "could not apply". WARNING: Your change was built on top of build 4275271, which is broken. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when gce_x86_phone-userdebug_fastbuild3c_linux is green.
WARNING: The tip-of-tree(4275271) for git_master/gce_x86_phone-userdebug_fastbuild3c_linux may be broken.
Presubmit builds based on the tip-of-tree (4275271) and the
last-known-good-build(4274798) also fail. This could be due to the
pre-existing error, a new error in this change, or both.



=== git_master/sailfish-userdebug_fastbuild3_linux ===

CONFLICT: Your changes failed to cherry-pick against build 4274798 (could not apply 3558538... Add ConnectivityManagerTest for Network.openConnection()). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4675033/sailfish-userdebug_fastbuild3_linux/latest and search for "could not apply". NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq
CONFLICT: Your changes failed to cherry-pick against build 4275271 (could not apply 3558538... Add ConnectivityManagerTest for Network.openConnection()). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4675032/sailfish-userdebug_fastbuild3_linux/latest and search for "could not apply". NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq. WARNING: Your change was built on top of build 4275271, which is likely to fail because the builds before and after it failed. Please check the continuous build at http://go/abbb/git_master/grid and retry your patch only when sailfish-userdebug_fastbuild3_linux is green.
WARNING: The tip-of-tree(4275271) for git_master/sailfish-userdebug_fastbuild3_linux may be broken.
Presubmit builds based on the tip-of-tree (4275271) and the
last-known-good-build(4274798) also fail. This could be due to the
pre-existing error, a new error in this change, or both.



=== git_master/test_suites_x86_64_fastbuild3d_linux ===

SKIPPED: Tests were skipped for git_master/test_suites_x86_64_fastbuild3d_linux/4275271 (ToT). Internal error: cannot find a successful build output for target test_suites_x86_64_fastbuild3d_linux
CONFLICT: Your changes failed to cherry-pick against build 4275271 (could not apply 3558538... Add ConnectivityManagerTest for Network.openConnection()). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4675026/test_suites_x86_64_fastbuild3d_linux/latest and search for "could not apply". NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq


=== git_master-art-host/art-test ===

PASS: Built git_master-art-host/art-test/4275186 (ToT). See https://android-build.googleplex.com/builds/pending/P4675025/art-test/latest


===

Have a question? Found a bug? http://go/treehugger-troubleshoot

Patch-set: 13
Tag: autogenerated:TreeHugger:Verify-Fail
Reviewer: Gerrit User 1062513 <1062513@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Verified=-1