Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> frameworks/base/core/java/android/content/pm/PackageList.java:54: error: method does not override or implement a method from a supertype
> @Override
> ^
> frameworks/base/core/java/android/content/pm/PackageList.java:57: error: cannot find symbol
> mWrappedObserver.onPackageChanged(packageName, uid);
> ^
> symbol: method onPackageChanged(String,int)
> location: variable mWrappedObserver of type PackageListObserver
> 2 errors

Sorry about that.
I test it only on Q, forgot to check the code base of aosp/master branch

Patch-set: 2
Reviewer: Gerrit User 1102879 <1102879@85c56323-6fa9-3386-8a01-6480fb634889>