Update patch set 1
Patch Set 1: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in AOSP.
  The following snippet of `git apply` output may point you in the right direction:
error: media/libmedia/MediaScannerClient.cpp: No such file or directory


Patchset creates merge conflict in Google's internal tree.

If you wish to pursue this change, please rebase and upload a new patchset.

Patch-set: 1
Reviewer: Gerrit User 1006433 <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=0
Label: Verified=-1