Update patch set 3
Patch Set 3: Fails; I would prefer that you didn't submit this

Clean cherry-pick to resolve merge path conflict.

The code doesn't build on the current master:

frameworks/base/telephony/java/com/android/internal/telephony/gsm/GsmServiceStateTracker.java:1284: cannot find symbol
symbol  : variable PROPERTY_ICC_OPERATOR_NUMERIC
location: class com.android.internal.telephony.gsm.GsmServiceStateTracker
	String simNumeric = SystemProperties.get(PROPERTY_ICC_OPERATOR_NUMERIC, "");

My other concerns still apply

Patch-set: 3
Reviewer: Gerrit User 1000660 <1000660@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=-1
Label: Verified=-1