Update patch set 5
Patch Set 5: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in Google's internal tree.

Patchset creates merge conflict in AOSP.
  The following snippet of `git apply` output may point you in the right direction:
error: patch failed: core/java/android/net/MobileDataStateTracker.java:41
error: core/java/android/net/MobileDataStateTracker.java: patch does not apply
error: patch failed: services/java/com/android/server/ConnectivityService.java:76
error: services/java/com/android/server/ConnectivityService.java: patch does not apply
error: patch failed: services/java/com/android/server/NetworkManagementService.java:107
error: services/java/com/android/server/NetworkManagementService.java: patch does not apply
error: telephony/java/com/android/internal/telephony/DataCallState.java: No such file or directory


If you wish to pursue this change, please rebase and upload a new patchset.

Patch-set: 5
Label: Code-Review=0
Label: Verified=-1