WMS:fix NPE due to the array store the null value in InsetsStateController.
  Short crash log as below:
  java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.InsetsSourceControl.getType()' on a null object reference
  at com.android.server.wm.InsetsStateController$1.notifyInsetsControlChanged(InsetsStateController.java:80)
  at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$3(InsetsStateController.java:343)
  at com.android.server.wm.InsetsStateController.$r8$lambda$8yykPRG1GyNq_J17QvL9d5xANMc(Unknown Source:0)
  at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda2.run(Unknown Source:2)

  The array store the null due to the method getControl in InsetsSourceProvider return the null value.

Test: Manual
Bug: 340445972
Change-Id: Ib6e0b332c39954dcac1fdeacfad7108c50805a14