fix missing comment in @deprecated javadoc tag
Fixes the following build error when building full-eng:

Docs droiddoc: out/target/common/docs/doc-comment-check
frameworks/base/core/java/com/android/internal/widget/LockPatternUtils.java:1280: error 114: @deprecated tag with no explanatory comment

Change-Id: I58085049311982a66565e53c85fbdf87ec7edca9