Update patch set 4
Patch Set 4: Fails

This is an automated message from the Deckard Autoverifier:

This patchset fails to build in the public AOSP source tree.  The following snippet of output from `make` may point you in the right direction:

frameworks/base/policy/src/com/android/internal/policy/impl/PhoneWindowManager.java:1086: cannot find symbol
symbol  : variable LID_CLOSE
location: class com.android.internal.policy.impl.PhoneWindowManager
                mLidOpen = LID_CLOSE;
                           ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
make: *** [out/target/common/obj/JAVA_LIBRARIES/android.policy_intermediates/classes-full-debug.jar] Error 41

If your patchset has a dependency in a separate project and you believe that this is the cause of the breakage, a reviewer can verify +1 and Deckard will remove the verify -1 shortly thereafter.

Otherwise, if you wish to pursue this change, please fix the error and upload a new patchset.

Thanks!

Patch-set: 4