Fix NPE problem in SurfaceControl#checkPreconditions
When calling SurfaceControl.Transaction.setCornerRadius(), a null SurfaceControl object is passed in, causing the checkPreconditions() method to directly call sc.checkNotReleased() without checking whether sc is null.

log:
java.lang.NullPointerException: Attempt to invoke direct method 'void android.view.SurfaceControl.checkNotReleased()' on a null object reference
	at android.view.SurfaceControl.-$$Nest$mcheckNotReleased(Unknown Source:0)
	at android.view.SurfaceControl$Transaction.checkPreconditions(SurfaceControl.java:3171)
	at android.view.SurfaceControl$Transaction.setCornerRadius(SurfaceControl.java:3810)
	at android.view.SurfaceControl$Transaction.setCornerRadius(SurfaceControl.java:3795)
	at com.android.wm.shell.transition.DefaultTransitionHandler.applyTransformation(go/retraceme 564b14c5b02dadf8816b06bc0337720dbb3b5504d3e70eacab9dafe993324723:409)
	at com.android.wm.shell.transition.DefaultTransitionHandler$$ExternalSyntheticLambda7.onAnimationUpdate(go/retraceme 564b14c5b02dadf8816b06bc0337720dbb3b5504d3e70eacab9dafe993324723:51)
	at android.animation.Animator$AnimatorCaller.lambda$static$4(Animator.java:855)

Signed-off-by:
Shuangxi Xiang <xiangshuangxi@xiaomi.corp-partner.google.com>

Change-Id: I71768c81b68f0d5359b9a0fa6a349198f6144d8c