Update patch set 4
Patch Set 4: Fails

Indeed, that's a lot of unnecessary whitespace changes that were introduced in Patch Set 4.

While that existing whitespace might technically violate the Android style guide and new code shouldn't be written with such whitespace, such broad changes of existing whitespace tend to cause more pain than keeping the whitespace itself: anyone who has changes in that are of the code downstream from the open-source master would then face unnecessary merge conflicts.

With that in mind, it'd be great to submit a new patch set with the whitespace unchanged.

I'm also not quite sure that this code compiles properly. I'm getting the following build error on my machine:

--------
frameworks/base/services/java/com/android/server/InputMethodManagerService.java:1520: cannot find symbol
symbol  : class Map
location: class com.android.server.InputMethodManagerService
            final Map<CharSequence, InputMethodInfo> imMap =
                  ^
frameworks/base/services/java/com/android/server/InputMethodManagerService.java:1521: cannot find symbol
symbol  : class TreeMap
location: class com.android.server.InputMethodManagerService
                new TreeMap<CharSequence, InputMethodInfo>(Collator.getInstance());
                    ^
frameworks/base/services/java/com/android/server/InputMethodManagerService.java:1521: cannot find symbol
symbol  : variable Collator
location: class com.android.server.InputMethodManagerService
                new TreeMap<CharSequence, InputMethodInfo>(Collator.getInstance());
--------

Patch-set: 4
Label: Code-Review=0
Label: Verified=-1