Update patch set 1
Patch Set 1: Presubmit-Ready+1

Looks like unrelated crashes from TH:

	DragDropControllerTests.testDragFlow (com.android.server.wm) 	26.708
 Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Process crashed.''. Check device logcat for details
Crash Message:Invalid column MAX(case when (date_added >= 157680000 and date_added < 1892160000) then date_added * 1000 when (date_added >= 157680000000 and date_added < 1892160000000) then date_added when (date_added >= 157680000000000 and date_added < 1892160000000000) then date_added / 1000 else 0 end)
java.lang.IllegalArgumentException: Invalid column MAX(case when (date_added >= 157680000 and date_added < 1892160000) then date_added * 1000 when (date_added >= 157680000000 and date_added < 1892160000000) then date_added when (date_added >= 157680000000000 and date_added < 1892160000000000) then date_added / 1000 else 0 end)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:169)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:139)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:420)
	at android.content.ContentResolver.query(ContentResolver.java:827)
	at android.content.ContentResolver.query(ContentResolver.java:775)
	at android.content.ContentResolver.query(ContentResolver.java:733)
	at acod.a(PG:7)
	at acoe.a(PG:24)
	at mbc.a(PG:66)
	at flf.a(PG:7)
	at acns.b(PG:11)
	at acnp.run(PG:6)

Crash Message:OutOfMemoryError thrown while trying to throw an exception; no stack trace available
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available

Patch-set: 1
Reviewer: Gerrit User 1149384 <1149384@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=+1