Ensure SEARCH_SERVICE is running
The SearchManager may be instantiated without SEARCH_SERVICE running,
resulting in a null pointer exception:

FATAL EXCEPTION: main
Process: com.google.android.apps.wearable.settings, PID: 711
java.lang.NullPointerException: Attempt to invoke interface method 'android.app.SearchableInfo android.app.ISearchManager.getSearchableInfo(android.content.ComponentName)' on a null object reference
	at android.app.SearchManager.getSearchableInfo(SearchManager.java:848)
 	at android.app.SearchDialog.show(SearchDialog.java:255)
	at android.app.SearchDialog.doShow(SearchDialog.java:227)
	at android.app.SearchDialog.show(SearchDialog.java:209)
	at android.app.SearchManager.startSearch(SearchManager.java:628)
	at android.app.SearchManager.startSearch(SearchManager.java:602)
	at android.app.Activity.startSearch(Activity.java:3907)
	at android.app.Activity.onSearchRequested(Activity.java:3856)
	at android.app.Activity.onSearchRequested(Activity.java:3845)
	at com.android.internal.policy.PhoneWindow.launchDefaultSearch(PhoneWindow.java:3100)
	at com.android.internal.policy.PhoneWindow.onKeyUp(PhoneWindow.java:2024)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:328)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4331)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4032)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4193)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2400)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1964)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1955)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2377)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

Add a check in launchDefaultSearch function so the search request won't be
transmitted to any search callback if the service is not running.

Bug: 64434057
Change-Id: I2edd452b89df80110ab7982061e8dd95f2c484e0
Signed-off-by: Gaëlle Nassiet <gaellex.nassiet@intel.com>