Update patch set 6
Patch Set 6: Presubmit-Ready+1

After running 5000 times, the original issue is not found.
But there is another timing issue will make test case failed.
The timing is occurred when default network doesn't switch to wifi yet and we do assertEquals(mWiFiNetworkAgent.getNetwork(), mCm.getActiveNetwork());.
I think adding waitForIdle() could fix this issue.
I will run another 1000 times to check if that timing issue could be fixed by adding waitForIdle().

BTW, the fail rate is around 0.76%.

[1/1] com.android.server.ConnectivityServiceTest#testPartialConnectivity: FAILED (786ms)

STACKTRACE:
java.lang.AssertionError: expected:<104> but was:<100>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.android.server.ConnectivityServiceTest.testPartialConnectivity(ConnectivityServiceTest.java:2658)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:148)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:919)

Summary
-------
FrameworksNetTests: Passed: 4962, Failed: 38, Ignored: 0 

38 tests failed
---------------

Patch-set: 6
Reviewer: Gerrit User 1308163 <1308163@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=+1