[ActivityManager] Fix IndexOutOfBoundsException
Symptom:
The stack was deleted during cleanup, so the stack
list size has reduced by one and cause this issue.

IndexOutOfBoundsException: Invalid index 1, size is 1

Change-Id: Ic6722aed98a0ad789b331d00e89cb74bf3b36d4c