Fix: Failed to get dump of alarm for proto
Symptom:
"dumpsys alarm --proto" was failed due to NullPointerException.

java.lang.NullPointerException: Attempt to invoke virtual method
'void android.app.PendingIntent.writeToProto(...)' on a null object
reference
 at android.app.AlarmManager$AlarmClockInfo.writeToProto()

Change-Id: I3ab838d3311979d3282004671c12536fb5cd5d2b