Allow priv apps to use VINTF services.
Specifically so that vendor apps can use VINTF services.

FIXME:
frameworks/base/core/java/android/os/ServiceManager.java:296: error: Attempting to unhide method android.os.ServiceManager.waitForDeclaredService(String), but surrounding class android.os.ServiceManager is hidden and should also be annotated with @android.annotation.SystemApi(clien
t=android.annotation.SystemApi.Client.PRIVILEGED_APPS) [ShowingMemberInHiddenClass]Error: metalava detected the following problems:
frameworks/base/core/java/android/os/ServiceManager.java:296: error: Attempting to unhide method android.os.ServiceManager.waitForDeclaredService(String), but surrounding class android.os.ServiceManager is hidden and should also be annotated with @android.annotation.SystemApi(clien
t=android.annotation.SystemApi.Client.PRIVILEGED_APPS) [ShowingMemberInHiddenClass]

Bug: 227289255
Test: wip
Change-Id: Ifd05f34eede64ca17d617616bb24ae30724fd9f4