Update patch set 2
Patch Set 2: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in AOSP.
  The following snippet of `git apply` output may point you in the right direction:
<stdin>:2306: trailing whitespace.

error: patch failed: packages/SettingsProvider/src/com/android/providers/settings/DatabaseHelper.java:34
error: packages/SettingsProvider/src/com/android/providers/settings/DatabaseHelper.java: patch does not apply
error: patch failed: telephony/java/android/telephony/PhoneStateListener.java:22
error: telephony/java/android/telephony/PhoneStateListener.java: patch does not apply
error: telephony/java/com/android/internal/telephony/BaseCommands.java: No such file or directory
error: telephony/java/com/android/internal/telephony/CallManager.java: No such file or directory
error: telephony/java/com/android/internal/telephony/CommandException.java: No such file or directory
...

Patchset creates merge conflict in Google's internal tree.

If you wish to pursue this change, please rebase and upload a new patchset.

Patch-set: 2
Reviewer: Gerrit User 1006433 <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=0
Label: Verified=-1