Update patch set 7
Patch Set 7: Fails

This is an automated message from the Deckard Autoverifier:

This patchset fails to build in the public AOSP source tree.  The following snippet of output from `make` may point you in the right direction:

frameworks/base/core/java/com/android/internal/os/ZygoteConnection.java:237: cannot find symbol
symbol  : method forkAndSpecialize(int,int,int[],int,int[][],java.lang.String,java.lang.String)
location: class dalvik.system.Zygote
            pid = Zygote.forkAndSpecialize(parsedArgs.uid, parsedArgs.gid,
                        ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

If your patchset has a dependency in a separate project and you believe that this is the cause of the breakage, a reviewer can verify +1 and Deckard will remove the verify -1 shortly thereafter.

Otherwise, if you wish to pursue this change, please fix the error and upload a new patchset.

Thanks!

Patch-set: 7
Label: Code-Review=0