Update patch set 2
Patch Set 2: Fails

We might be missing some #include...

------
frameworks/base/core/jni/android_server_Watchdog.cpp: In function 'void dumpKernelStacks(JNIEnv*, _jobject*, _jstring*)':
frameworks/base/core/jni/android_server_Watchdog.cpp:66: error: 'S_IRUSR' was not declared in this scope
frameworks/base/core/jni/android_server_Watchdog.cpp:66: error: 'S_IWUSR' was not declared in this scope
frameworks/base/core/jni/android_server_Watchdog.cpp:66: error: 'S_IRGRP' was not declared in this scope
frameworks/base/core/jni/android_server_Watchdog.cpp:66: error: 'S_IWGRP' was not declared in this scope
frameworks/base/core/jni/android_server_Watchdog.cpp:66: error: 'S_IROTH' was not declared in this scope
frameworks/base/core/jni/android_server_Watchdog.cpp:66: error: 'S_IWOTH' was not declared in this scope
make: *** [out/target/product/passion/obj/SHARED_LIBRARIES/libandroid_runtime_intermediates/android_server_Watchdog.o] Error 1
------

Patch-set: 2