Add volatile to variable which lives through setjmp
Add volatile to variable fp to always reload from memory before using it,
otherwise compiler (eg. GCC 4.9) may put it in the register which is clobbered
when longjmp back.

Error message (with GCC 4.9) before this change reads

frameworks/base/tools/aapt/Images.cpp:1378:11: error: variable 'fp' might be clobbered by 'longjmp' or 'vfork' [-Werror=clobbered]
     FILE* fp;
           ^

Change-Id: I56f3f08aafd3840bfc8688820458136ec581149c