Fix broken ActivityManager service build when DEBUG_ALL = true ( @see ActivityManagerDebugConfig.java ) Also removed unjustified executable file permissions ( chmod a-x ActiveServices.java ActivityRecord.java  BaseErrorDialog.java ).
Problem:
ERROR: /home/ron/Android/aosp/master/frameworks/base/services/core/java/com/android/server/am/ActiveServices.java:1624: The local variable si may not have been initialized

Cause:
When setting DEBUG_ALL to true, the log statements may refer to an unitialized object, and jack build breaks.
Note to verifier: This is easy to miss since upon release DEBUG_ALL = false, so before verifying you must modify the DEBUG_ALL to true variable in ActivityManagerDebugConfig.java.
		  DO NOT commit any change in ActivityManagerDebugConfig.java - or the log will be a mess.

Fix:
Initialize all ServiceRecord.StartItem instances.

Change-Id: I8c623625c23b723d0964fd8574a023d0d95abfe9