Add StorageManager.convert() check earlier in the stack so the command fails early instead of crashing system later.
Bug: 393614518
BUG: 460779368
Flag: EXEMPT BUGFIX
Test: PackageInstallerServiceTest
Test: new error Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Invalid volumeUuid value in session params: ../../../data
	at com.android.server.am.ActiveServices$$ExternalSyntheticThrowBlockOutline3.m(R8$$SyntheticClass:0)
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:1045)
        ...

(cherry picked from commit fe2d4eb0555ab2f1ea812d2b12e0a1548edea2e7)
Cherrypick-From: https://googleplex-android-review.googlesource.com/q/commit:f10d91c07960e69b9d89f557a84e780c985d4178
Merged-In: Ifbd9c37565eae47d85ab3198b7bf76fe15a20b4f
Change-Id: Ifbd9c37565eae47d85ab3198b7bf76fe15a20b4f