Update patch set 6
Patch Set 6: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in Google's internal tree.

Patchset creates breakage in AOSP.
  The following snippet of `make` output may point you in the right direction:
external/bluetooth/bluedroid/Android.mk:8: NO BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR, using only generic configuration
find: `src': No such file or directory
frameworks/base/telephony/java/com/android/internal/telephony/Nat464xlatService.java:108: com.android.internal.telephony.Nat464xlatService.InterfaceObserver is not abstract and does not override abstract method interfaceClassDataActivityChanged(java.lang.String,boolean) in android.net.INetworkManagementEventObserver
    private class InterfaceObserver extends INetworkManagementEventObserver.Stub {
            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
...

If your patchset has a dependency in a separate project, please ensure that both changes are uploaded with the same Change-Id.

Patch-set: 6
Reviewer: Gerrit User 1006433 <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=0
Label: Verified=-1