Update patch set 8
Patch Set 8:

This is not going to work as is. The master build failed with:

=====
frameworks/base/services/core/java/com/android/server/job/JobStore.java:895: error: method setCapabilities in class NetworkCapabilities cannot be applied to given types;
request.networkCapabilities.setCapabilities(
^
required: int[],int[]
found: int[]
=====

The easiest fix for this would be to re-add back the setCapabilities() method that takes an int[], while maintaining the version that takes two int[]. Presumably the one-arg version would set the unwanted capability bits. After the CL automerges into master you can fix the callers in master (or not, if this is the expected behaviour).

Also, I think one of the AOSP builds failed with:

=====
frameworks/base/../../frameworks/base/core/java/android/net/NetworkRequest.java:156: lint: Unresolved link/see tag "#addUnwantedCapability(int)" in android.net.NetworkRequest.Builder [101]
=====

I think this is because addUnwantedCapability is still @hide in this CL. That means you can't refer to it in Javadoc. I would just remove the @see tag in this CL and re-add it in the follow-up CL when you un-@hide addUnwantedCapability.

Patch-set: 8
Reviewer: Gerrit User 1000835 <1000835@85c56323-6fa9-3386-8a01-6480fb634889>