[Bugfix] add synchronized control for access of mValidateUids
// exception caused by concurrent access of mValidateUids
FATAL EXCEPTION IN SYSTEM PROCESS: android.fg
java.lang.ArrayIndexOutOfBoundsException: src.length=159 srcPos=124 dst.length=159 dstPos=125 length=-81
at java.lang.System.arraycopy(Native Method)
at com.android.internal.util.GrowingArrayUtils.insert(GrowingArrayUtils.java:135)
at android.util.SparseArray.put(SparseArray.java:280)
at com.android.server.am.ActiveUids.put(ActiveUids.java:48)
at com.android.server.am.UidObserverController.dispatchUidsChanged(UidObserverController.java:294)
at com.android.server.am.UidObserverController$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:249)
at android.os.Looper.loop(Looper.java:337)
at android.os.HandlerThread.run(HandlerThread.java:85)
at com.android.server.ServiceThread.run(ServiceThread.java:46)

Signed-off-by: zhoutongyu <zhoutongyu@xiaomi.com>
Change-Id: Ib80942daa7483c1683066c2330b58674d956d4c7