Update patch set 3
Patch Set 3: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in AOSP.
  The following snippet of `git apply` output may point you in the right direction:
error: telephony/java/com/android/internal/telephony/BaseCommands.java: No such file or directory
error: telephony/java/com/android/internal/telephony/CommandException.java: No such file or directory
error: telephony/java/com/android/internal/telephony/CommandsInterface.java: No such file or directory
error: telephony/java/com/android/internal/telephony/Connection.java: No such file or directory
error: telephony/java/com/android/internal/telephony/PhoneBase.java: No such file or directory
error: telephony/java/com/android/internal/telephony/RIL.java: No such file or directory
error: patch failed: telephony/java/com/android/internal/telephony/RILConstants.java:300
error: telephony/java/com/android/internal/telephony/RILConstants.java: patch does not apply
error: telephony/java/com/android/internal/telephony/cat/AppInterface.java: No such file or directory
...

Patchset creates merge conflict in Google's internal tree.

If you wish to pursue this change, please rebase and upload a new patchset.

Patch-set: 3
Reviewer: Gerrit User 1006433 <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=0
Label: Verified=-1